POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRldGUiLCJpZCI6IjYwNWExZmMzMzU2MTY2MmI5MDRkZTY4YyIsImlhdCI6MTYxNjU3MDI3OH0.BnFnqFPBuHNKCzg6eVZ6UawuEnlo59bgEgbr19jHndY

{
  "title": "testtitle",
  "author": "testauthor",
  "url": "testurl",
  "likes": 0
}

